version: '3'

tasks:
  app:run:
    desc: "Run the Dart app on host (usage: task app:run -- test|prod)"
    silent: true
    cmds:
      - |
        case "{{.CLI_ARGS}}" in
          "test"|"")
            CLICKUP_ENV_FILE=app/runtime/env/clickup.test.yaml dart run app/lib/main.dart
            ;;
          "prod")
            CLICKUP_ENV_FILE=app/runtime/env/clickup.prod.yaml dart run app/lib/main.dart
            ;;
          *)
            echo "Error: Invalid argument '{{.CLI_ARGS}}'. Use 'test' or 'prod'"
            exit 1
            ;;
        esac

  app:build:
    desc: "Build the app image (usage: task app:build IMAGE_TAG)"
    silent: true
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ] || [ "{{.CLI_ARGS}}" = "dev" ]; then
          IMAGE_TAG=dev docker compose -f infrastructure/docker/compose.yaml build app
        else
          ACCOUNT_NAME=rksilvergreen IMAGE_TAG={{.CLI_ARGS}} docker compose -f infrastructure/docker/compose.yaml build app
        fi

  app:start:
    desc: "Start the app container (usage: task app:start -- test|prod [IMAGE_TAG])"
    silent: true
    cmds:
      - |
        case "{{.CLI_ARGS}}" in
          "test"|"")
            if [ -z "{{index .CLI_ARGS 1}}" ] || [ "{{index .CLI_ARGS 1}}" = "dev" ]; then
              CLICKUP_ENV_FILE=../../app/runtime/env/clickup.test.yaml IMAGE_TAG=dev docker compose -p clickup-listener-test -f infrastructure/docker/compose.yaml up app
            else
              CLICKUP_ENV_FILE=../../app/runtime/env/clickup.test.yaml ACCOUNT_NAME=rksilvergreen IMAGE_TAG={{index .CLI_ARGS 1}} docker compose -p clickup-listener-test -f infrastructure/docker/compose.yaml up app
            fi
            ;;
          "prod")
            if [ -z "{{index .CLI_ARGS 1}}" ] || [ "{{index .CLI_ARGS 1}}" = "dev" ]; then
              CLICKUP_ENV_FILE=../../app/runtime/env/clickup.prod.yaml IMAGE_TAG=dev docker compose -p clickup-listener-prod -f infrastructure/docker/compose.yaml up app
            else
              CLICKUP_ENV_FILE=../../app/runtime/env/clickup.prod.yaml ACCOUNT_NAME=rksilvergreen IMAGE_TAG={{index .CLI_ARGS 1}} docker compose -p clickup-listener-prod -f infrastructure/docker/compose.yaml up app
            fi
            ;;
          *)
            echo "Error: Invalid argument '{{.CLI_ARGS}}'. Use 'test' or 'prod'"
            exit 1
            ;;
        esac

  app:stop:
    desc: "Stop the app container (usage: task app:stop -- test|prod [IMAGE_TAG])"
    silent: true
    cmds:
      - |
        case "{{.CLI_ARGS}}" in
          "test"|"")
            if [ -z "{{index .CLI_ARGS 1}}" ] || [ "{{index .CLI_ARGS 1}}" = "dev" ]; then
              IMAGE_TAG=dev docker compose -p clickup-listener-test -f infrastructure/docker/compose.yaml down app
            else
              ACCOUNT_NAME=rksilvergreen IMAGE_TAG={{index .CLI_ARGS 1}} docker compose -p clickup-listener-test -f infrastructure/docker/compose.yaml down app
            fi
            ;;
          "prod")
            if [ -z "{{index .CLI_ARGS 1}}" ] || [ "{{index .CLI_ARGS 1}}" = "dev" ]; then
              IMAGE_TAG=dev docker compose -p clickup-listener-prod -f infrastructure/docker/compose.yaml down app
            else
              ACCOUNT_NAME=rksilvergreen IMAGE_TAG={{index .CLI_ARGS 1}} docker compose -p clickup-listener-prod -f infrastructure/docker/compose.yaml down app
            fi
            ;;
          *)
            echo "Error: Invalid argument '{{.CLI_ARGS}}'. Use 'test' or 'prod'"
            exit 1
            ;;
        esac

  app:logs:
    desc: "Show app container logs (usage: task app:logs -- test|prod [IMAGE_TAG])"
    silent: true
    cmds:
      - |
        case "{{.CLI_ARGS}}" in
          "test"|"")
            if [ -z "{{index .CLI_ARGS 1}}" ] || [ "{{index .CLI_ARGS 1}}" = "dev" ]; then
              IMAGE_TAG=dev docker compose -p clickup-listener-test -f infrastructure/docker/compose.yaml logs -f --tail=100 app
            else
              ACCOUNT_NAME=rksilvergreen IMAGE_TAG={{index .CLI_ARGS 1}} docker compose -p clickup-listener-test -f infrastructure/docker/compose.yaml logs -f --tail=100 app
            fi
            ;;
          "prod")
            if [ -z "{{index .CLI_ARGS 1}}" ] || [ "{{index .CLI_ARGS 1}}" = "dev" ]; then
              IMAGE_TAG=dev docker compose -p clickup-listener-prod -f infrastructure/docker/compose.yaml logs -f --tail=100 app
            else
              ACCOUNT_NAME=rksilvergreen IMAGE_TAG={{index .CLI_ARGS 1}} docker compose -p clickup-listener-prod -f infrastructure/docker/compose.yaml logs -f --tail=100 app
            fi
            ;;
          *)
            echo "Error: Invalid argument '{{.CLI_ARGS}}'. Use 'test' or 'prod'"
            exit 1
            ;;
        esac

  tunnel:start:
    desc: "Open the Cloudflare tunnel using Docker Compose (usage: task tunnel:start -- test|prod)"
    silent: true
    cmds:
      - |
        case "{{.CLI_ARGS}}" in
          "test"|"")
            TUNNEL_ENV_FILE=../tunnel/tunnel.test.env docker compose -p clickup-listener-test -f infrastructure/docker/compose.yaml up tunnel
            ;;
          "prod")
            TUNNEL_ENV_FILE=../tunnel/tunnel.prod.env docker compose -p clickup-listener-prod -f infrastructure/docker/compose.yaml up tunnel
            ;;
          *)
            echo "Error: Invalid argument '{{.CLI_ARGS}}'. Use 'test' or 'prod'"
            exit 1
            ;;
        esac
  
  tunnel:stop:
    desc: "Stop the Cloudflare tunnel using Docker Compose (usage: task tunnel:stop -- test|prod)"
    silent: true
    cmds:
      - |
        case "{{.CLI_ARGS}}" in
          "test"|"")
            docker compose -p clickup-listener-test -f infrastructure/docker/compose.yaml down tunnel
            ;;
          "prod")
            docker compose -p clickup-listener-prod -f infrastructure/docker/compose.yaml down tunnel
            ;;
          *)
            echo "Error: Invalid argument '{{.CLI_ARGS}}'. Use 'test' or 'prod'"
            exit 1
            ;;
        esac

  tunnel:logs:
    desc: "Show tunnel container logs (usage: task tunnel:logs -- test|prod)"
    silent: true
    cmds:
      - |
        case "{{.CLI_ARGS}}" in
          "test"|"")
            docker compose -p clickup-listener-test -f infrastructure/docker/compose.yaml logs -f --tail=100 tunnel
            ;;
          "prod")
            docker compose -p clickup-listener-prod -f infrastructure/docker/compose.yaml logs -f --tail=100 tunnel
            ;;
          *)
            echo "Error: Invalid argument '{{.CLI_ARGS}}'. Use 'test' or 'prod'"
            exit 1
            ;;
        esac

  domain:switch:
    desc: "Switch {{.HOSTNAME}} to {local|remote}"
    silent: true
    dotenv: ['infrastructure/tunnel/cloudflare.env']
    vars:
      TARGET:     { sh: 'echo ${TARGET:-local}' }  # usage: task domain:switch TARGET=remote
      TTL:        "1"                             # 1 = auto (works when proxied)
      PROXIED:    "true"                          # true/false (boolean in JSON)
    preconditions:
      - sh: '[ -n "$HOSTNAME" ] && [ -n "$CF_ZONE_ID" ] && [ -n "$CF_RECORD_ID" ] && [ -n "$CF_API_TOKEN" ] && [ -n "$TUNNEL_PROD_LOCAL" ] && [ -n "$TUNNEL_PROD_REMOTE" ]'
        msg: "Missing required variables in cloudflare.env file"
    cmds:
      - |
        if [ "{{.TARGET}}" = "local" ]; then
          curl -sX PUT "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records/$CF_RECORD_ID" \
            -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type: application/json" \
            --data "{\"type\":\"CNAME\",\"name\":\"$HOSTNAME\",\"content\":\"$TUNNEL_PROD_LOCAL\",\"proxied\":{{.PROXIED}},\"ttl\":{{.TTL}}}"
        elif [ "{{.TARGET}}" = "remote" ]; then
          curl -sX PUT "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records/$CF_RECORD_ID" \
            -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type: application/json" \
            --data "{\"type\":\"CNAME\",\"name\":\"$HOSTNAME\",\"content\":\"$TUNNEL_PROD_REMOTE\",\"proxied\":{{.PROXIED}},\"ttl\":{{.TTL}}}"
        else
          echo "Usage: task domain:switch TARGET={local|remote}"; exit 1
        fi

  webhooks:activate:
    desc: "Activate ClickUp webhooks for the specified environment (usage: task webhooks:activate -- test|prod)"
    silent: true
    dotenv: ['infrastructure/clickup.env']
    cmds:
      - |
        case "{{.CLI_ARGS}}" in
          "test"|"")
            echo "Activating webhooks for TEST environment..."
            WEBHOOK_IDS="$WEBHOOK_IDS_TEST"
            ;;
          "prod")
            echo "Activating webhooks for PROD environment..."
            WEBHOOK_IDS="$WEBHOOK_IDS_PROD"
            ;;
          *)
            echo "Error: Invalid argument '{{.CLI_ARGS}}'. Use 'test' or 'prod'"
            exit 1
            ;;
        esac
        
        # Process webhook IDs - handle both single and comma-separated values
        if [ -n "$WEBHOOK_IDS" ]; then
          # Split comma-separated webhook IDs using parameter expansion
          # Replace commas with spaces for proper word splitting
          WEBHOOK_IDS_SPACED="${WEBHOOK_IDS//,/ }"
          
          for WEBHOOK_ID in $WEBHOOK_IDS_SPACED; do
            # Simple whitespace removal - remove leading/trailing spaces
            WEBHOOK_ID="${WEBHOOK_ID# }"
            WEBHOOK_ID="${WEBHOOK_ID% }"
            
            if [ -n "$WEBHOOK_ID" ]; then
              echo "Activating webhook ID: $WEBHOOK_ID"
              # Update webhook status to active
              curl -X PUT "https://api.clickup.com/api/v2/webhook/$WEBHOOK_ID" \
                -H "Authorization: $API_TOKEN" \
                -H "Content-Type: application/json" \
                -d '{"status": "active"}' \
                -w "\nHTTP Status: %{http_code}\n"
              echo "---"
            fi
          done
        else
          echo "No webhook IDs found for environment '{{.CLI_ARGS}}'"
        fi